// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/OrangePortraitEventPoster--PPWX6/DeepOrangePoster.tsx": () => import("../components/mockups/templates/OrangePortraitEventPoster--PPWX6/DeepOrangePoster.tsx"),
  "./components/mockups/templates/OrangePortraitEventPoster-HJm5Dg/DeepOrangePoster.tsx": () => import("../components/mockups/templates/OrangePortraitEventPoster-HJm5Dg/DeepOrangePoster.tsx"),
  "./components/mockups/templates/OrangePortraitEventPoster-IOATxN/DeepOrangePoster.tsx": () => import("../components/mockups/templates/OrangePortraitEventPoster-IOATxN/DeepOrangePoster.tsx"),
  "./components/mockups/templates/OrangePortraitEventPoster-mNVMhk/DeepOrangePoster.tsx": () => import("../components/mockups/templates/OrangePortraitEventPoster-mNVMhk/DeepOrangePoster.tsx")
};
